
sudo: required
dist: trusty
language: c
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Uodrn3x36plX2yk4+c7eimCuv7j6p6n1XCNbNEYxibRX77730eQMCVS0BvM40OgD7m5K9s2hIQaMV7EMj3qKuRmemULDVJVTgNd1fbx6t4BhYh+Hrf6FhsNcm9nFxvQQrdJAVSOwIAlrUilVFotDRt9qKqLwwZiBKIs5gBPcHQY="

addons:
    coverity_scan:
      project:
        name: "DaveDavenport/rofi"
        description: "Build submitted via Travis CI"
      notification_email: qball@gmpclient.org
      build_command_prepend: "autoreconf -i;./configure; make clean"
      build_command:   "make"
      branch_pattern: coverity_scan
    apt:
        packages:
            - autoconf
            - automake
            - make
            - xutils-dev
            - libpango1.0-dev
            - libcairo2-dev
            - libstartup-notification0-dev
            - libxcb-ewmh-dev
            - libxcb-icccm4-dev
            - libxcb-util0-dev
            - libxcb-xinerama0-dev
            - libxcb-xkb-dev
            - libxcb-randr0-dev
            - libxcb1-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - xvfb
            - discount
            - xdotool
            - fluxbox
            - xterm
            - gdb
            - lcov
            - doxygen
            - graphviz
            - texinfo
            - texi2html
            - xfonts-base

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y 'deb https://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse'
    - sudo add-apt-repository -y 'deb https://debian.jpleau.ca/ jessie-backports main contrib non-free'
    - sudo apt-get update -qq
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-


# TODO: We install xkbcommon here, until Travis use an up-to-date enough Ubuntu
install:
    - sudo apt-get install -y --force-yes flex/trusty-backports libfl-dev/trusty-backports
    - sudo apt-get install -y --force-yes python3.5-pip
    - pip3.5 install --user meson
    - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip
    - unzip ninja-linux.zip
    - export PATH=$(pwd):$PATH
    - git clone https://github.com/alobbs/doxy-coverage
    - git clone --recursive https://github.com/Airblader/xcb-util-xrm.git
    - cd xcb-util-xrm
    - ./autogen.sh --prefix=/usr
    - make
    - sudo make install
    - cd -
    - git clone https://github.com/libcheck/check/ -b 0.11.0
    - cd check
    - autoreconf -i
    - TEX="false" ./configure --prefix=/usr/
    - make
    - sudo make install
    - cd -

before_script:
    - meson build -Db_coverage=true

script:
    - ninja -C build
    - ninja -C build test
    - ulimit -c unlimited
    - ninja -C build test-x
    - ninja -C build doc/html 2>&1 > doxygen.log
    - test $(grep -c warning doxygen.log) -eq 0
    - ./doxy-coverage/doxy-coverage.py build/doc/html/xml/

after_success:
      - bash <(curl -s https://codecov.io/bash)

notifications:
    webhooks:
        urls:
            - secure: "AqDM5SkWJPSBeCiyGdXzHYLnFCML/vKxWW/0wE00ocX+97Fa5ixeU7apMJ0OMZ0ZQVXG96xVtlJ513ZSpnRYHx6FF+Ivvw5pYeZjKHqtxThEhOueW1YynYWMX7HJrA4P19ollqRLrtsJqG6x7BhVEnIyhyu9eXtgj6hiI70F0SE="
        on_success: change
