sudo: required
dist: trusty
language: c
addons:
    apt:
        packages:
            - autoconf
            - automake
            - make
            - xutils-dev
            - libx11-dev
            - libpango1.0-dev
            - libcairo2-dev
            - libstartup-notification0-dev
            - libxcb-icccm4-dev
            - libxcb-util0-dev
            - libxcb-xinerama0-dev
            - libxcb-xkb-dev
            - libxcb1-dev
            - xvfb
            - discount
            - xdotool
            - fluxbox

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y 'deb http://debian.jpleau.ca/ jessie-backports main contrib non-free'
    - sudo apt-get update -qq

# TODO: We install xkbcommon here, until Travis use an up-to-date enough Ubuntu
# TODO: We install libxcb-ewmh-dev here, until it is whitelisted again in Travis
install:
    - sudo apt-get install -y --force-yes libxkbcommon-dev libxkbcommon-x11-dev libxcb-ewmh-dev

before_script:
    - git clone --recursive https://github.com/Airblader/xcb-util-xrm.git
    - cd xcb-util-xrm 
    - ./autogen.sh --prefix=/usr
    - make
    - sudo make install
    - cd -
    - autoreconf -i
    - ./configure --enable-gcov

script:
    - make
    - make check
# to re-enable if xdotool is allowed.
    - make test-x
    - make test-x1
    - gcov source/rofi.c
    - make distcheck

after_success:
      - bash <(curl -s https://codecov.io/bash)
